In [14]:
# PS8

In [81]:
# Problem 1
# Using a decision tree classifier to predict Y given X
clf = DecisionTreeClassifier()
clf.fit(X, Y)
# 5-fold validation to compute acuuracy of prediction
scores = cross_val_score(clf, X, Y, cv=5) 
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

# Creating a truth matrix
y_pred = cross_val_predict(clf, X, Y, cv=5)
conf_matrix = confusion_matrix(Y, y_pred)
print(conf_matrix)

# Adjusting class weight 
clf2 = DecisionTreeClassifier(class_weight = 'balanced')
clf.fit(X, Y)
# 5 fold validation score
scores2 = cross_val_score(clf2, X, Y, cv=5)
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
y_pred2 = cross_val_predict(clf2, X, Y, cv=5)
conf_matrix2 = confusion_matrix(Y, y_pred2)
print(conf_matrix2)

# Results
print('FN' ,((264-204)/264)*100, '% less')
print('TN' ,((247-237)/237)*100, '% less')
print('TP' ,((92454-92394)/92394)*100, '% more')
print('FP' ,((246-236)/236)*100, '% more')
print('RR Lyrae detection rate' , (237/(204+237)))
"""
Adjusting the class weight to being balanced reduced the number of false negatives by 22.7% and
reduced the number of true negatives by 4.2%. The number of true positives also increased by.065% and 
the number of false positives also increased by 4.2%.
Overall this is more accurate, because the number of false negatives was reduced by 22.7%, resulting in a 
53% detection rate of RR Lyrae stars.

"""

Accuracy: 0.99 (+/- 0.00)
[[92415   243]
 [  236   247]]
Accuracy: 0.99 (+/- 0.00)
[[92449   209]
 [  246   237]]


In [2]:
# Imports 
import numpy as np
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix, plot_confusion_matrix

In [3]:
# Read given data
def read_data(name):
    X = np.genfromtxt(name + '_features.txt', delimiter=',')
    Y = np.genfromtxt(name + '_labels.txt')
    return X, Y

name = "RRLyrae"
X, Y = read_data(name)

In [4]:
# Problem 1
def decision_tree_RRLyrae(X, Y, clf):
    clf.fit(X, Y)
    # 5-fold validation to compute acuuracy of prediction
    scores = cross_val_score(clf, X, Y, cv=5) 
    print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
    
"""
Truth Matrix format:
[TP, FN]
[FP, TN]
"""   
def truth_matrix_RRLyrae(clf):
    y_pred = cross_val_predict(clf, X, Y, cv=5)
    conf_matrix = confusion_matrix(Y, y_pred)
    print(conf_matrix)
    return conf_matrix
    
def decision_tree_results(matrix1, matrix2):
    TP1 = matrix1[0][0]
    FN1 = matrix1[0][1]
    FP1 = matrix1[1][0]
    TN1 = matrix1[1][1]

    TP2 = matrix2[0][0]
    FN2 = matrix2[0][1]
    FP2 = matrix2[1][0]
    TN2 = matrix2[1][1]

    
    print('FN' ,((FN2-FN1)/FN1)*100, '% change')
    print('TN' ,((TN2-TN1)/TN1)*100, '% change')
    print('TP' ,((TP2-TP1)/TP1)*100, '% change')
    print('FP' ,((FP2-FP1)/FP1)*100, '% change')
    print('RR Lyrae detection rate 1' ,((TN1/(FN1+TN1))))
    print('RR Lyrae detection rate 2' ,((TN2/(FN2+TN2))))
    print('RR Lyrae detection rate change' , (((TN2/(FN2+TN2)))-((TN1/(FN1+TN1))))*100, '% change')

In [19]:
def call_decision_tree_truth_matrix_results(clf, matrix_name, matrix1):
    decision_tree_RRLyrae(X, Y, DecisionTreeClassifier(class_weight = 'balanced'))
    matrix_name = truth_matrix_RRLyrae(DecisionTreeClassifier(class_weight = 'balanced'))
    decision_tree_results(matrix1, matrix_name)
    
call_decision_tree_truth_matrix_results(DecisionTreeClassifier(class_weight = 'balanced'), truth_matrix_22, truth_matrix_1)

In [5]:
# Accuracy and truth matrix for decision tree
decision_tree_RRLyrae(X, Y, DecisionTreeClassifier())
truth_matrix_1 = truth_matrix_RRLyrae(DecisionTreeClassifier())

Accuracy: 0.99 (+/- 0.00)
[[92410   248]
 [  236   247]]


In [6]:
# Accuracy and truth matrix for decision tree with weight class set to balanced
decision_tree_RRLyrae(X, Y, DecisionTreeClassifier(class_weight = 'balanced'))
truth_matrix_2 = truth_matrix_RRLyrae(DecisionTreeClassifier(class_weight = 'balanced'))
decision_tree_results(truth_matrix_1, truth_matrix_2)

Accuracy: 1.00 (+/- 0.00)
[[92450   208]
 [  245   238]]
FN -16.129032258064516 % change
TN -3.643724696356275 % change
TP 0.043285358727410454 % change
FP 3.8135593220338984 % change
RR Lyrae detection rate 1 0.498989898989899
RR Lyrae detection rate 2 0.5336322869955157
RR Lyrae detection rate change 3.4642388005616698 % change


In [36]:
"""
Setting the class weight to balanced is more accurate. It decreased the number of False negatives by 18%. 
Overall, the RR Lyrae detection rate has increased by 3.46%
"""

0.48336594911937375


'\nTruth Matrix format:\n[TP, FN]\n[FP, TN]\n\nOnly 1% of the data are RR lyrae stars. The negative, which coorelates to being RR Lyrae has only a 49.3% accuracy\nas 255 were false negatives, while only 251 were true negatives.\n\n'

In [ ]:
"""
In this case, we want detect as many RR Lyrae stars as possible, even if it means a higher false negative rate. 
The depth that gives the highest number of RR Lyrae detections is best.
"""

In [22]:
# Accuracy and truth matrix for decision tree with max depth set to 3
decision_tree_RRLyrae(X, Y, DecisionTreeClassifier(max_depth=3))
truth_matrix_3 = truth_matrix_RRLyrae(DecisionTreeClassifier(max_depth=3))
decision_tree_results(truth_matrix_1, truth_matrix_3)

Accuracy: 0.99 (+/- 0.00)
[[92473   185]
 [  389    94]]
FN -25.403225806451612 % change
TN -61.943319838056674 % change
TP 0.06817443999567147 % change
FP 64.83050847457628 % change
RR Lyrae detection rate 1 0.498989898989899
RR Lyrae detection rate 2 0.33691756272401435
RR Lyrae detection rate change -16.20723362658846 % change


In [23]:
# Accuracy and truth matrix for decision tree with max depth set to 4
decision_tree_RRLyrae(X, Y, DecisionTreeClassifier(max_depth=4))
truth_matrix_4 = truth_matrix_RRLyrae(DecisionTreeClassifier(max_depth=4))
decision_tree_results(truth_matrix_1, truth_matrix_4)

Accuracy: 1.00 (+/- 0.00)
[[92386   272]
 [  183   300]]
FN 9.67741935483871 % change
TN 21.45748987854251 % change
TP -0.025971215236446275 % change
FP -22.45762711864407 % change
RR Lyrae detection rate 1 0.498989898989899
RR Lyrae detection rate 2 0.5244755244755245
RR Lyrae detection rate change 2.5485625485625496 % change


In [25]:
# Accuracy and truth matrix for decision tree with max depth set to 5
decision_tree_RRLyrae(X, Y, DecisionTreeClassifier(max_depth=5))
truth_matrix_5 = truth_matrix_RRLyrae(DecisionTreeClassifier(max_depth=5))
decision_tree_results(truth_matrix_1, truth_matrix_5)

Accuracy: 1.00 (+/- 0.00)
[[92439   219]
 [  198   285]]
FN -11.693548387096774 % change
TN 15.384615384615385 % change
TP 0.03138188507737258 % change
FP -16.101694915254235 % change
RR Lyrae detection rate 1 0.498989898989899
RR Lyrae detection rate 2 0.5654761904761905
RR Lyrae detection rate change 6.648629148629148 % change


In [ ]:
"""
Max depth 5 was the best, as it gave the highest rate of TN, accurately detected RR Lyrae. 
The FP rate was also the lowest.
"""

In [26]:
# Accuracy and truth matrix for decision tree with max depth set to 5
decision_tree_RRLyrae(X, Y, DecisionTreeClassifier(max_depth=5, class_weight='balanced'))
truth_matrix_6 = truth_matrix_RRLyrae(DecisionTreeClassifier(max_depth=5, class_weight='balanced'))
decision_tree_results(truth_matrix_1, truth_matrix_6)

Accuracy: 0.98 (+/- 0.01)
[[90537  2121]
 [   26   457]]
FN 755.241935483871 % change
TN 85.02024291497976 % change
TP -2.0268369224109946 % change
FP -88.98305084745762 % change
RR Lyrae detection rate 1 0.498989898989899
RR Lyrae detection rate 2 0.17726920093095422
RR Lyrae detection rate change -32.17206980589447 % change
